### ISSUE TITLE
what performance will be if depth prediction is trained alone without other semantic branches?

### ISSUE THREAD

**Issue by sconlyshootery** [joe-siyuan-qiao/ViP-DeepLab#1]
Thank you for your wonderful work, I just want to know what performance will be if depth prediction is trained alone without other semantic branches?

**Comment by joe-siyuan-qiao** [comment]
For our results on the KITTI Depth Benchmark (Sec. 5.3), the depth prediction is trained alone without other semantic branches -- the dataset does not provide any supervision for those branches, so they are omitted during training/inference.

**Comment by sconlyshootery** [comment]
Thank you, help me a lot.
