### ISSUE TITLE
How to convert cityscapes-vps dataset to citescapes like?

### ISSUE THREAD

**Issue by lxa9867** [joe-siyuan-qiao/ViP-DeepLab#2]
Hello, thank you for providing such a great work.

I am trying to convert cityscapes-vps dataset to cityscapes like, however cityscapes-vps didn't provide the json files which describes the panoptic labels. Could you please tell me how to convert the dataset? Thank you!

**Comment by joe-siyuan-qiao** [comment]
Please raise this issue to cityscapes-vps. Thanks.
