### ISSUE TITLE
Will you provide the code of the proposed model?

### ISSUE THREAD

**Issue by xjturobocon** [joe-siyuan-qiao/ViP-DeepLab#3]
Thanks for your work! Do you have the plan to open source the code of the peoposed model?

**Comment by joe-siyuan-qiao** [comment]
We don't know yet. But if we plan to release the codes, they will be very likely found here:

https://github.com/tensorflow/models/tree/master/research/deeplab

Please stay tuned.

**Comment by rodrigoGA** [comment]
@joe-siyuan-qiao  congratulations on this project.

Do you have news about the publication of the model? I am doing a university project and I am very interested in testing your model

Thanks
