### ISSUE TITLE
About SemanticKITTI-DVPS

### ISSUE THREAD

**Issue by p-andra** [joe-siyuan-qiao/ViP-DeepLab#4]
Thank you for your work!

Regarding the semantic images from SemanticKITTI-DVPS, they seem to be pretty sparse compared to the ones in the paper. Do you process the semantic image in order to obtain more dense segments, if so, how?

![semantic](https://user-images.githubusercontent.com/4256560/106203727-86eb8b80-61c4-11eb-80e0-f0b6c482c672.png)

**Comment by joe-siyuan-qiao** [comment]
Thanks for the question. The paper shows densified annotations for visualization purpose only. For training and evaluation, we used sparse annotations as what you showed here.

**Comment by p-andra** [comment]
Thank you!
