### ISSUE TITLE
About calculation of depth loss for points without supervision

### ISSUE THREAD

**Issue by cahity** [joe-siyuan-qiao/ViP-DeepLab#5]
Hey. Thank you for your great research. Loved it! This issue will be only about the depth estimation task.

Did you only calculate loss for points which has their ground-truth labels?

Side question regarding this; since the points from an object can come from its every point, model should learn to predict smooth results in order to minimize the loss even though the GT is sparse. So, can we say that this is actually a weakly-supervised method?

**Comment by joe-siyuan-qiao** [comment]
Thanks for the question. Yes, the loss is computed only for the points with labels. And yes, it is kind of a weakly supervised method from this perspective.
