### ISSUE TITLE
About the SemanticKITTI-DVPS label names.

### ISSUE THREAD

**Issue by HarborYuan** [joe-siyuan-qiao/ViP-DeepLab#8]
Hi,
Thanks for your great work. Currently, I am working on my own project on SemanticKITTI-DVPS. I am wondering what is the label names of the dataset, since it seems different from both the Cityscapes and the original Semantic KITTI datasets. Can I find the name corresponding to each class id in some place? 

Thanks.

**Comment by joe-siyuan-qiao** [comment]
Hi @HarborYuan 

Thanks for the question. The SemanticKITTI label names can be found here:

https://github.com/PRBonn/semantic-kitti-api/blob/master/config/semantic-kitti-all.yaml#L144

The difference is that in SemKITTI-DVPS we make 255 unlabeled, and shift the rest IDs by 1, i.e., 0: car, 1: bicycle, 2: motorcycle, and so on.

Hope it helps.

**Comment by HarborYuan** [comment]
Thanks for your response.
And I guess the "moving" classes are merged (so that 0-18, 'car' to 'traffic sign' are valid classes), while 0-7 ('car' to 'motorcyclist') are things, right?

**Comment by joe-siyuan-qiao** [comment]
Yes, that's correct.

**Comment by HarborYuan** [comment]
Thanks, that's very helpful.
